# Generated by Django 2.0.1 on 2018-11-07 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=50, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
